Set WindowBar Colorful

Set Width 1920
Set Height 1080

Set CursorBlink false

Set Theme "nord"

Set Shell zsh
Type "jbang jtextvm"
Enter
Sleep 4s
Down 3
Sleep 3s
Type "2"
Sleep 1.5s
Type "3"
Sleep 2s
Down 7
Sleep 2.5s
Down 11
Sleep 3s
Type "231"
Sleep 1.5s
Down
Sleep 1.5s
Type "3"
Sleep 2s
Type "21"
Down 7
Sleep 2.5s
Type "2"
Sleep 2s
Type "3"
Sleep 3.5s
Type "21"
Up 10
Down
Up 4
Sleep 1.5s
Type "23"
Sleep 2.5s
Type "e"
Sleep 1.5s
Type "e"
Sleep 2s
Type "q"
Sleep 2.5s
Ctrl+D