Source shared_.tape

# Setup
Hide
Type jbang markdown-demo
Enter
Sleep 3
Show

# Recording
Sleep 2s
Screenshot screenshots/markdown-demo.svg
Type "j"
Sleep 500ms
Type "j"
Sleep 500ms
Type "j"
Sleep 500ms
Type "j"
Sleep 500ms
Type "j"
Sleep 1s
Type "k"
Sleep 500ms
Type "k"
Sleep 500ms
Type "k"
Sleep 500ms
Type "k"
Sleep 500ms
Type "k"
Sleep 1s
Type "s"
Sleep 15s
Type "s"
Sleep 1s
Type "j"
Sleep 500ms
Type "j"
Sleep 500ms
Type "j"
Sleep 500ms
Type "j"
Sleep 1s
Type "q"
